#!/bin/bash
set -euo pipefail

SR_VERSION=3.16.1
AIFC_VERSION=3.13.0
CHUNK_VERSION=3.13.0

OUT=/tmp/py-debs
mkdir -p "$OUT"

WORK=$(mktemp -d)

build_pypi_deb() {
  local pypi_name=$1
  local deb_name=$2
  local version=$3
  local extra_depends=$4

  local sdist_url
  sdist_url=$(curl -fsSL "https://pypi.org/pypi/${pypi_name}/${version}/json" \
    | jq -r '.urls[] | select(.packagetype == "sdist") | .url')

  local sdist_filename="${sdist_url##*/}"

  cd "$WORK"
  rm -f "$sdist_filename"
  curl -fsSL -o "$sdist_filename" "$sdist_url"
  local sdist_dir
  sdist_dir=$(tar tzf "$sdist_filename" | head -1 | cut -d/ -f1)
  rm -rf "$sdist_dir"
  tar xzf "$sdist_filename"
  cd "$sdist_dir"

  mkdir -p debian/source

  cat > debian/control <<EOF
Source: ${deb_name}
Section: python
Priority: optional
Maintainer: PX4 Build CI <noreply@invalid>
Build-Depends: debhelper-compat (= 13),
 dh-python,
 pybuild-plugin-pyproject,
 python3-all,
 python3-setuptools (>= 77),
 python3-wheel
Standards-Version: 4.6.2
Rules-Requires-Root: no

Package: ${deb_name}
Architecture: all
Depends: \${misc:Depends}, python3${extra_depends:+, ${extra_depends}}
Description: ${pypi_name} ${version} (auto-built from PyPI sdist)
 Auto-generated by build-py-debs.sh for the PX4 companion image.
EOF

  cat > debian/rules <<'EOF'
#!/usr/bin/make -f
export PYBUILD_DISABLE = test

%:
	dh $@ --with python3 --buildsystem=pybuild
EOF
  chmod +x debian/rules

  echo "3.0 (quilt)" > debian/source/format

  cat > debian/changelog <<EOF
${deb_name} (${version}-1) unstable; urgency=medium

  * Auto-built from PyPI sdist ${sdist_filename}.

 -- PX4 Build CI <noreply@invalid>  $(date -R)
EOF

  dpkg-buildpackage -us -uc -b
  cp ../"${deb_name}"_*.deb "$OUT/"
}

build_pypi_deb standard-chunk    python3-standard-chunk    "$CHUNK_VERSION" ""
build_pypi_deb standard-aifc     python3-standard-aifc     "$AIFC_VERSION"  "python3-standard-chunk, python3-audioop-lts"
build_pypi_deb SpeechRecognition python3-speechrecognition "$SR_VERSION"    "python3-typing-extensions, python3-audioop-lts, python3-standard-aifc"

ls -la "$OUT/"
